-- Time Travel Theater Database Schema
-- Run this in your Supabase SQL Editor

-- Drop existing tables if they exist (to start fresh)
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS showtimes CASCADE;
DROP TABLE IF EXISTS movies CASCADE;

-- Drop existing functions and triggers (after tables are dropped)
DROP FUNCTION IF EXISTS update_available_seats() CASCADE;

-- Enable Row Level Security
ALTER DEFAULT PRIVILEGES REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;

-- Movies table
CREATE TABLE movies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  year INTEGER NOT NULL,
  duration INTEGER NOT NULL, -- in minutes
  genre VARCHAR(255) NOT NULL,
  description TEXT,
  poster_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Showtimes table
CREATE TABLE showtimes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movie_id BIGINT REFERENCES movies(id) ON DELETE CASCADE,
  show_date DATE NOT NULL,
  show_time TIME NOT NULL,
  theater_room VARCHAR(50) NOT NULL DEFAULT 'Main Theater',
  total_seats INTEGER NOT NULL DEFAULT 100,
  available_seats INTEGER NOT NULL DEFAULT 100,
  price DECIMAL(10,2) NOT NULL DEFAULT 12.00,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Bookings table
CREATE TABLE bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  showtime_id BIGINT REFERENCES showtimes(id) ON DELETE CASCADE,
  seats TEXT[] NOT NULL, -- Array of seat numbers
  total_price DECIMAL(10,2) NOT NULL,
  booking_status VARCHAR(20) DEFAULT 'confirmed' CHECK (booking_status IN ('confirmed', 'cancelled', 'pending')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_showtimes_movie_id ON showtimes(movie_id);
CREATE INDEX IF NOT EXISTS idx_showtimes_date ON showtimes(show_date);
CREATE INDEX IF NOT EXISTS idx_bookings_user_id ON bookings(user_id);
CREATE INDEX IF NOT EXISTS idx_bookings_showtime_id ON bookings(showtime_id);

-- Enable Row Level Security (RLS)
ALTER TABLE movies ENABLE ROW LEVEL SECURITY;
ALTER TABLE showtimes ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;

-- RLS Policies

-- Movies: Public read access
CREATE POLICY "Movies are publicly readable" ON movies
  FOR SELECT USING (true);

-- Movies: Only admins can insert/update (for now, allow all authenticated users)
CREATE POLICY "Authenticated users can manage movies" ON movies
  FOR ALL USING (auth.role() = 'authenticated');

-- Showtimes: Public read access
CREATE POLICY "Showtimes are publicly readable" ON showtimes
  FOR SELECT USING (true);

-- Showtimes: Only authenticated users can manage
CREATE POLICY "Authenticated users can manage showtimes" ON showtimes
  FOR ALL USING (auth.role() = 'authenticated');

-- Bookings: Users can only see their own bookings
CREATE POLICY "Users can view their own bookings" ON bookings
  FOR SELECT USING (auth.uid() = user_id);

-- Bookings: Users can create their own bookings
CREATE POLICY "Users can create their own bookings" ON bookings
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Bookings: Users can update their own bookings
CREATE POLICY "Users can update their own bookings" ON bookings
  FOR UPDATE USING (auth.uid() = user_id);

-- Function to update available seats when booking is made
CREATE OR REPLACE FUNCTION update_available_seats()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    -- Decrease available seats
    UPDATE showtimes 
    SET available_seats = available_seats - array_length(NEW.seats, 1)
    WHERE id = NEW.showtime_id;
    RETURN NEW;
  ELSIF TG_OP = 'UPDATE' THEN
    -- If booking status changed to cancelled, increase available seats
    IF OLD.booking_status != 'cancelled' AND NEW.booking_status = 'cancelled' THEN
      UPDATE showtimes 
      SET available_seats = available_seats + array_length(NEW.seats, 1)
      WHERE id = NEW.showtime_id;
    END IF;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    -- Increase available seats when booking is deleted
    UPDATE showtimes 
    SET available_seats = available_seats + array_length(OLD.seats, 1)
    WHERE id = OLD.showtime_id;
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for automatic seat management
CREATE TRIGGER trigger_update_available_seats
  AFTER INSERT OR UPDATE OR DELETE ON bookings
  FOR EACH ROW
  EXECUTE FUNCTION update_available_seats();

-- Insert sample data
INSERT INTO movies (title, year, duration, genre, description) VALUES
  ('Back to the Future', 1985, 116, 'Sci-Fi, Adventure', 'A teenager is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his friend Dr. Emmett Brown.'),
  ('Groundhog Day', 1993, 101, 'Comedy, Fantasy', 'A narcissistic, self-centered weatherman finds himself in a time loop on Groundhog Day.'),
  ('The Terminator', 1984, 107, 'Sci-Fi, Action', 'A cyborg assassin is sent back in time to kill the mother of humanity''s future savior.'),
  ('12 Monkeys', 1995, 129, 'Sci-Fi, Thriller', 'In a future world devastated by disease, a convict is sent back in time to gather information about the man-made virus.'),
  ('About Time', 2013, 123, 'Romance, Comedy', 'A young man discovers he can travel back in time and tries to improve his life.'),
  ('Looper', 2012, 119, 'Sci-Fi, Action', 'In 2074, when the mob wants to get rid of someone, the target is sent into the past, where a looper kills and disposes of them.');

-- Insert sample showtimes for today and tomorrow
DO $$
DECLARE
  movie_record RECORD;
  today DATE := CURRENT_DATE;
  tomorrow DATE := CURRENT_DATE + INTERVAL '1 day';
BEGIN
  FOR movie_record IN SELECT id FROM movies LOOP
    -- Today's showtimes
    INSERT INTO showtimes (movie_id, show_date, show_time, price) VALUES
      (movie_record.id, today, '14:00', 12.00),
      (movie_record.id, today, '17:30', 15.00),
      (movie_record.id, today, '20:45', 15.00);
    
    -- Tomorrow's showtimes
    INSERT INTO showtimes (movie_id, show_date, show_time, price) VALUES
      (movie_record.id, tomorrow, '13:00', 12.00),
      (movie_record.id, tomorrow, '16:15', 15.00),
      (movie_record.id, tomorrow, '19:30', 15.00);
  END LOOP;
END $$;